
// Films
export const GET_CURRENT_FILMS_START = "GET_CURRENT_FILMS_START";
export const GET_CURRENT_FILMS_SUCCESS ="GET_CURRENT_FILMS_SUCCESS";
export const GET_CURRENT_FILMS_ERROR = "GET_CURRENT_FILMS_ERROR";
export const FILTER_CURRENT_FILMS = "FILTER_CURRENT_FILMS";
export const SET_FILM = "SET_FILM";
export const GET_CINEMA_DAYS = "GET_CINEMA_DAYS";

//TICKET
export const BUY_TICKET_START = "BUY_TICKET_START";
export const BUY_TICKET_SUCCESS = "BUY_TICKET_SUCCESS";
export const BUY_TICKET_ERROR = "BUY_TICKET_ERROR";
export const CLEAR_TICKET_PAGE = "CLEAR_TICKET_PAGE";

