// Films

export const GET_CURRENT_FILMS_START = "GET_CURRENT_FILMS_START";
export const GET_CURRENT_FILMS_SUCCESS ="GET_CURRENT_FILMS_SUCCESS";
export const GET_CURRENT_FILMS_ERROR = "GET_CURRENT_FILMS_ERROR";
export const FILTER_CURRENT_FILMS = "FILTER_CURRENT_FILMS";
export const SET_FILM = "SET_FILM";


